import {gunzipSync} from 'node:zlib';
import {parseSyncTeX} from '../shared/synctex.mjs';
import {copyLatexImages} from './writeup-assets.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import {bundledTectonic} from './desktop-tools.mjs';
import {spawn} from 'node:child_process';
import {createHash,randomUUID} from 'node:crypto';
import {projectFile} from './axiovela/assistant-api.mjs';
import {stopProcess} from './axiovela/assistant-process.mjs';
export function runCommand(command,args,cwd,timeout=120000,signal){return new Promise(resolve=>{if(signal?.aborted)return resolve({exitCode:null,output:'',canceled:true});const child=spawn(command,args,{cwd,detached:process.platform!=='win32',stdio:['ignore','pipe','pipe']});let output='',timedOut=false,done=false;const finish=result=>{if(done)return;done=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);resolve({...result,output,timedOut,canceled:!!signal?.aborted});};const abort=()=>stopProcess(child);signal?.addEventListener('abort',abort,{once:true});const timer=setTimeout(()=>{timedOut=true;stopProcess(child);},timeout);for(const stream of [child.stdout,child.stderr])stream.on('data',c=>{output=(output+c.toString()).slice(-30000);});child.on('error',e=>finish({exitCode:null,error:e.code==='ENOENT'?'Tool is not installed or not on PATH.':e.message}));child.on('close',code=>finish({exitCode:code}));});}
export async function inspectLean(root,run=false,recordDir,options={}){const file=await projectFile(root,'certificates/Main.lean',true);const record={id:randomUUID(),checkedAt:new Date().toISOString(),status:'not-configured',checks:[],formalCertificate:false};let source='';try{source=await fs.readFile(file,'utf8');}catch(e){if(e.code!=='ENOENT')throw e;record.checks.push({label:'Theorem source',status:'missing',detail:'Ask the formalization assistant to create the certificate project.'});if(options.save!==false)await saveCheck(root,record,recordDir);return record;}
 record.sourceHash=createHash('sha256').update(source).digest('hex');record.checks.push({label:'Theorem source',status:'present',detail:'A source snapshot was found. Source is kept out of this view.'});
 for(const [name,label] of [['lean-toolchain','Pinned Lean toolchain'],['lake-manifest.json','Locked dependencies']]){try{const text=await fs.readFile(await projectFile(root,'certificates/'+name),'utf8');record.checks.push({label,status:'present',detail:name==='lean-toolchain'?text.trim():'Dependency lockfile found; its contents still require audit.'});}catch{record.checks.push({label,status:'missing',detail:'Required for reproducible checking.'});}}
 const admissions=/\b(sorry|admit|axiom)\b/.test(source);record.checks.push({label:'Admission preflight',status:admissions?'attention':'clear',detail:admissions?'Potential admission or axiom found. This text scan includes comments.':'No obvious admission tokens in the entry file. Dependencies are not certified by this scan.'});
 record.checks.push({label:'Statement correspondence',status:'review-required',detail:'A mathematician must check that the formal statement matches the claimed result.'});record.status='preflight';
 if(run&&record.checks.filter(c=>c.status==='missing').length===0){const result=await runCommand(options.lake||process.env.AXIOVELA_LAKE_PATH||'lake',['env','lean','Main.lean'],path.dirname(file),120000,options.signal);record.command='lake env lean Main.lean';record.exitCode=result.exitCode;record.diagnostics=result.output;record.status=result.canceled?'canceled':result.error?'tool-unavailable':result.timedOut?'timed-out':result.exitCode===0?'build-passed':'build-failed';record.message=result.error|| (record.status==='build-passed'?'Entry file compiled. Full dependency, axiom and statement audits are still required.':'The checker reported a failure; ask the assistant to explain and repair it.');const after=await fs.readFile(file,'utf8');if(createHash('sha256').update(after).digest('hex')!==record.sourceHash){record.status='stale';record.message='The source changed during the check. Run it again.';}}
 if(options.save!==false)await saveCheck(root,record,recordDir);return record;}
export async function compileLatex(root,source,bibliography){if(typeof source!=='string'||source.length>1_000_000)throw Error('LaTeX source is missing or too large.');const id=randomUUID();const dir=await projectFile(root,`exports/${id}`,true);await fs.mkdir(dir,{recursive:true});await fs.writeFile(path.join(dir,'main.tex'),source);await copyLatexImages(root,source,dir);if(typeof bibliography==='string')await fs.writeFile(path.join(dir,'references.bib'),bibliography);else try{await fs.copyFile(await projectFile(root,'references.bib'),path.join(dir,'references.bib'));}catch(e){if(e.code!=='ENOENT')throw e;}const executable=process.env.WORKBENCH_LATEX_PATH||bundledTectonic()||'tectonic';const result=await runCommand(executable,['--untrusted','--synctex','--keep-logs','--outdir',dir,path.join(dir,'main.tex')],dir);if(result.error||result.exitCode!==0)throw Error(result.error||'LaTeX compilation failed. '+result.output.slice(-4000));await fs.access(path.join(dir,'main.pdf'));let sourceMap=[];try{sourceMap=parseSyncTeX(gunzipSync(await fs.readFile(path.join(dir,'main.synctex.gz'))).toString());}catch{/* A valid PDF remains usable if source navigation is unavailable. */}return {id,sourceHash:createHash('sha256').update(source).digest('hex'),sourceMap};}

async function saveCheck(root,record,recordDir){const file=recordDir?path.join(recordDir,record.id+'.json'):await projectFile(root,`certificates/checks/${record.id}.json`,true);await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,JSON.stringify(record,null,2));}
