import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {chromium} from 'playwright';
const data=await fs.mkdtemp(path.join(os.tmpdir(),'axiovela-math-feedback-'));
const url='http://127.0.0.1:8793';
const env={...process.env,PORT:'8793',AXIOVELA_MATH_DATA:data,AXIOVELA_BRIDGE_DISCOVERY_PATHS:path.join(data,'none'),WORKBENCH_PROVIDER_SETTINGS_PATH:path.join(data,'private/providers.json'),WORKBENCH_CODEX_PATH:path.resolve('scripts/fixtures/assistant-rpc.mjs'),AXIOVELA_LAKE_PATH:'/nonexistent/fixture-lake'};
for(const key of ['OPENAI_API_KEY','ANTHROPIC_API_KEY','GEMINI_API_KEY','GOOGLE_API_KEY','WORKBENCH_COMPATIBLE_API_KEY'])delete env[key];
const service=spawn(process.execPath,['server/index.mjs'],{env,stdio:'pipe'});let browser,page;
const checks=[];
try{
 for(let i=0;i<100;i++){try{if((await fetch(url+'/api/state')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 const initial=await(await fetch(url+'/api/state')).json(),first=initial.activeProjectId;
 browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1560,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);
 const root=(await(await fetch(url+'/api/project-root?project='+first)).json()).folder;
 assert.equal(await page.getByLabel('research task',{exact:true}).count(),0);
 assert.equal(await page.getByRole('button',{name:/Load saved (summary|proof)|Export proof/}).count(),0);
 await fs.writeFile(path.join(root,'research/summary.md'),'## Automatically updated summary');
 await fs.writeFile(path.join(root,'research/proof.md'),'## Automatically updated argument');
 await page.getByRole('heading',{name:'Automatically updated summary'}).waitFor();
 await page.getByRole('heading',{name:'Automatically updated argument'}).waitFor();
 await page.getByRole('button',{name:'Edit',exact:true}).nth(1).click();
 await page.getByLabel('Proof write-up source').fill('## My corrected argument');
 await page.waitForFunction(()=>!localStorage.getItem('axiovela-math-pending-workspace'));
 await page.reload();await page.getByRole('heading',{name:'My corrected argument'}).waitFor();
 await fs.writeFile(path.join(root,'research/proof.md'),'## Assistant revision');
 await page.getByRole('button',{name:'Review changes'}).click();
 await page.getByRole('dialog').getByRole('heading',{name:'My corrected argument'}).waitFor();
 await page.getByRole('button',{name:'Keep my version'}).click();
 await page.waitForFunction(()=>!localStorage.getItem('axiovela-math-pending-workspace'));
 await page.reload();await page.getByRole('heading',{name:'My corrected argument'}).waitFor();
 await page.waitForResponse(r=>r.url().includes('/api/research-artifacts'));
 assert.equal(await page.getByRole('button',{name:'Review changes'}).count(),0);
 await fs.writeFile(path.join(root,'research/proof.md'),'## Further assistant revision');
 await page.getByRole('button',{name:'Review changes'}).click();await page.getByRole('button',{name:'Use assistant version'}).click();
 await page.getByRole('heading',{name:'Further assistant revision'}).waitFor();
 await page.getByLabel('File menu').click();await page.getByRole('button',{name:'Research version history'}).click();
 await page.getByRole('dialog').locator('summary').click();await page.getByRole('dialog').getByRole('heading',{name:'My corrected argument'}).waitFor();
 await page.getByRole('button',{name:'Restore this version'}).click();await page.getByRole('heading',{name:'My corrected argument'}).waitFor();
 checks.push('Research removes task, manual load and proof export controls','saved research documents update automatically','saved local edits survive reload and remote changes','keep, accept and restore research revisions');
 await page.getByRole('button',{name:'Write-up',exact:true}).click();await page.getByLabel('Manuscript source').fill('# Local original');await page.getByRole('button',{name:'Save source',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('axiovela-math-pending-sources')||'[]').length===0);
 await fs.writeFile(path.join(root,'writeups/main.md'),'# External revision');
 await page.getByLabel('Manuscript source').fill('# Unsaved local revision');await page.getByRole('button',{name:'Save source',exact:true}).click();await page.getByText('The project file differs from this editor.',{exact:false}).waitFor();assert.equal(await page.getByLabel('Manuscript source').inputValue(),'# Unsaved local revision');assert.equal(await fs.readFile(path.join(root,'writeups/main.md'),'utf8'),'# External revision');checks.push('stale source save preserves both editor and external file');
 await page.getByLabel('Preview actions').click();const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Export source',exact:true}).click();await page.getByLabel('Preview actions').click();assert.equal((await downloadEvent).suggestedFilename(),'main.md');
 await page.getByLabel('Write-up actions').click();await page.getByRole('button',{name:'Load assistant’s saved draft',exact:true}).click();await page.getByLabel('Write-up actions').click();await page.waitForFunction(()=>document.querySelector('[aria-label="Manuscript source"]').value==='# External revision');checks.push('source export and explicit disk reload');
 await page.waitForFunction(()=>!localStorage.getItem('axiovela-math-pending-workspace'));
 await page.getByRole('button',{name:'Bibliography',exact:true}).click();const bib='@article{one,title={Fixture},author={Example, A},year={2026}}';await page.getByLabel('BibTeX bibliography').fill(bib);await page.getByRole('button',{name:'Save bibliography',exact:true}).click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('axiovela-math-pending-sources')||'[]').length===0);assert.equal(await fs.readFile(path.join(root,'references.bib'),'utf8'),bib);await page.getByRole('button',{name:'Close dialog'}).click();checks.push('bibliography writes a real project file');
 await page.getByRole('button',{name:'LaTeX',exact:false}).first().click();
 await page.route('**/api/render?*',r=>r.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'Fixture compilation failure'})}));await page.getByRole('button',{name:'Render PDF',exact:true}).click();await page.getByRole('alert').filter({hasText:'Fixture compilation failure'}).waitFor();assert.equal(await page.getByRole('button',{name:'Render PDF',exact:true}).isEnabled(),true);checks.push('render failure leaves an enabled retry');await page.unroute('**/api/render?*');
 let release,entered;const gate=new Promise(r=>release=r),started=new Promise(r=>entered=r);
 await page.route('**/api/render?*',async r=>{entered();await gate;await r.fulfill({contentType:'application/json',body:JSON.stringify({id:'11111111-1111-1111-1111-111111111111'})});});
 await page.route('**/api/rendered?*',r=>r.fulfill({contentType:'application/pdf',body:Buffer.from('%PDF-1.4\n%%EOF')}));
 await page.getByRole('button',{name:'Render PDF',exact:true}).click();await started;
 await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByLabel('Project folder',{exact:true}).fill('Second fixture');await page.getByRole('button',{name:'Open or create',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});release();await page.getByRole('button',{name:'LaTeX',exact:false}).first().click();assert.equal(await page.getByRole('region',{name:'Publication PDF'}).count(),0);
 await page.getByRole('button',{name:'Untitled mathematics project',exact:true}).click();await page.getByRole('region',{name:'Publication PDF'}).waitFor();assert.ok((await page.getByRole('link',{name:'Open PDF'}).getAttribute('href')).includes(first));checks.push('late render stays with its originating project');
 await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByLabel('Project folder',{exact:true}).fill('Second fixture');await page.getByRole('button',{name:'Open or create',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal(await page.getByRole('button',{name:'Second fixture',exact:true}).count(),1);await page.getByRole('button',{name:'Untitled mathematics project',exact:true}).click();checks.push('opening a known project folder reuses the existing tab');
 await page.getByRole('button',{name:'Research',exact:true}).click();await page.getByRole('button',{name:'Choose research model and provider'}).click();await page.getByRole('button',{name:'Use model',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByLabel('research message').fill('FIXTURE_HANG');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.getByRole('button',{name:'Stop conversation',exact:true}).waitFor();
 await fs.writeFile(path.join(root,'research/summary.md'),'## Summary after stopped turn');
 const deferred=await(await fetch(url+'/api/research-artifacts?project='+first)).json();assert.equal(deferred.working,true);assert.equal(deferred.artifacts,undefined);
 checks.push('research synchronization waits for running conversations');
 await page.getByLabel('research message').fill('Queued fixture');await page.getByRole('button',{name:'Queue follow-up',exact:true}).click();await page.getByRole('button',{name:'Stop conversation',exact:true}).click();await page.getByRole('button',{name:'Resume queue',exact:true}).waitFor();await page.locator('.queueItem').getByRole('button',{name:'Edit',exact:true}).click();await page.getByLabel('Edit queued message').fill('FIXTURE_LONG_CHAT');await page.getByRole('button',{name:'Save edit',exact:true}).click();await page.getByRole('button',{name:'Resume queue',exact:true}).click();await page.getByRole('heading',{name:'Diagnostic 12',exact:true}).waitFor();
 // Wait for streaming to finish before testing a deliberate scroll away from the latest reply.
 await page.getByRole('button',{name:'Stop conversation',exact:true}).waitFor({state:'hidden'});
 await page.locator('.chatMessages').evaluate(e=>e.scrollTop=0);await page.getByRole('button',{name:'Jump to latest'}).click();checks.push('chat stop, queued edit, resume and Jump to latest');
 await page.getByLabel('research message').fill('Draft in first chat');const selected=await page.getByLabel('research conversation',{exact:true}).inputValue();await page.getByRole('button',{name:'New research conversation',exact:true}).click();await page.waitForFunction(id=>document.querySelector('select[aria-label="research conversation"]').value!==id,selected);await page.getByLabel('research message').fill('Draft in second chat');await page.getByLabel('research conversation',{exact:true}).selectOption(selected);assert.equal(await page.getByLabel('research message').inputValue(),'Draft in first chat');checks.push('new chat keeps separate drafts');
 let releaseResearch,enteredResearch;
 const researchGate=new Promise(r=>releaseResearch=r),researchStarted=new Promise(r=>enteredResearch=r);
 await page.route('**/api/research-artifacts?project='+first,async r=>{enteredResearch();await researchGate;await r.fulfill({contentType:'application/json',body:JSON.stringify({working:false,artifacts:{summary:{text:'## Delayed first-project summary',hash:'delayed-fixture'}}})});});
 await researchStarted;await page.getByRole('button',{name:'Second fixture',exact:true}).click();
 const lateResponse=page.waitForResponse(r=>r.url().includes('/api/research-artifacts?project='+first));releaseResearch();await lateResponse;
 await page.waitForResponse(r=>r.url().includes('/api/research-artifacts')&&!r.url().includes(first));
 assert.equal(await page.getByRole('heading',{name:'Delayed first-project summary'}).count(),0);
 await page.unroute('**/api/research-artifacts?project='+first);checks.push('late research update cannot cross project boundaries');
 await page.getByRole('button',{name:'Lean Certificates',exact:true}).click();await page.getByRole('button',{name:'Run Lean check'}).click();await page.getByRole('heading',{name:'No formal source saved yet',exact:true}).waitFor();checks.push('Lean run reports missing project without fabricated success');
 assert.deepEqual(errors,[]);checks.push('no JavaScript runtime errors');await fs.writeFile('docs/feedback-validation.json',JSON.stringify({passed:true,checks,checkedAt:new Date().toISOString(),liveCredentialsUsed:false},null,2)+'\n');console.log(JSON.stringify(checks));
}catch(e){if(page)await page.screenshot({path:'.local/qa/feedback-failure.png'});throw e;}finally{await browser?.close();service.kill('SIGTERM');await new Promise(r=>service.once('exit',r));await fs.rm(data,{recursive:true,force:true});}
