import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {chromium} from 'playwright';
const data=await fs.mkdtemp(path.join(os.tmpdir(),'axiovela-math-ui-'));
const port=8792,url=`http://127.0.0.1:${port}`;
const env={...process.env,PORT:String(port),AXIOVELA_MATH_DATA:data,AXIOVELA_BRIDGE_DISCOVERY_PATHS:path.join(data,'none'),WORKBENCH_PROVIDER_SETTINGS_PATH:path.join(data,'private/providers.json'),WORKBENCH_CODEX_PATH:path.resolve('scripts/fixtures/assistant-rpc.mjs'),AXIOVELA_LAKE_PATH:'/nonexistent/fixture-lake'};
for(const id of ['CLAUDE','GEMINI','OPENCODE','PI'])env[`WORKBENCH_${id}_PATH`]=path.resolve('scripts/fixtures/provider-cli.mjs');
for(const key of ['OPENAI_API_KEY','ANTHROPIC_API_KEY','GEMINI_API_KEY','GOOGLE_API_KEY','WORKBENCH_COMPATIBLE_API_KEY'])delete env[key];
const service=spawn(process.execPath,['server/index.mjs'],{env,stdio:'pipe'});let logs='';service.stderr.on('data',x=>logs+=x);
let browser,page;
try{
 for(let i=0;i<100;i++){try{if((await fetch(url+'/api/state')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 assert.equal((await fetch(url+'/api/state',{headers:{Origin:'https://untrusted.example'}})).status,403);
 browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1600,height:1040}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.getByRole('heading',{name:'Executive summary'}).waitFor();
 await page.evaluate(async()=>{const s=await(await fetch('/api/state')).json();Object.assign(s.projects[0],{question:'Fixture: examine a precise mathematical conjecture.',summary:'## Current approach\n\nA fixture for the revised workspace. No research result is asserted.'});await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json','If-Match':String(s.revision)},body:JSON.stringify(s)});});await page.reload();await page.getByRole('heading',{name:'Current approach'}).waitFor();assert.equal(await page.getByRole('button',{name:'Edit',exact:true}).count(),0);
 const splitter=page.getByRole('separator').first();const before=await splitter.getAttribute('aria-valuenow');await splitter.focus();await page.keyboard.press('ArrowRight');assert.notEqual(await splitter.getAttribute('aria-valuenow'),before);await page.waitForFunction(async()=>{const s=await(await fetch('/api/state')).json();return s.projects[0].question.startsWith('Fixture:');});await page.reload();assert.notEqual(await page.getByRole('separator').first().getAttribute('aria-valuenow'),before);await page.getByRole('button',{name:'Reset layout'}).click();assert.equal(await page.getByRole('separator').first().getAttribute('aria-valuenow'),before);
 await page.getByRole('button',{name:'Choose research model and provider'}).click();await page.getByRole('button',{name:'Use model',exact:true}).waitFor();await page.getByRole('button',{name:'Use model',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByLabel('research message').fill('FIXTURE_CODE');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.getByText('Get-Location',{exact:false}).waitFor();
 await page.getByLabel('research message').fill('FIXTURE_ATTEMPT');await page.getByRole('button',{name:'Send message',exact:true}).click();
 await page.waitForFunction(async()=>{const s=await(await fetch('/api/state')).json();const r=await(await fetch('/api/proof-attempts?project='+s.activeProjectId+'&query=spectral')).json();return r.total===1&&r.shown===1&&r.attempts[0].status==='blocked';});
 await page.getByRole('button',{name:'Choose research model and provider'}).click();await page.locator('dialog[open] select').first().selectOption('claude');await page.getByText('Install or connect Claude Code',{exact:true}).waitFor();await page.getByRole('button',{name:'Windows',exact:true}).click();await page.getByText('npm.cmd install -g @anthropic-ai/claude-code',{exact:true}).waitFor();await page.getByRole('button',{name:'Close model picker'}).click();
 await fs.mkdir('.local/qa',{recursive:true});await page.screenshot({path:'.local/qa/research-redesign.png'});
 const sharedConversation=await page.getByLabel('research conversation',{exact:true}).inputValue();await page.getByLabel('research message').fill('Unsent shared research draft');await page.getByRole('button',{name:'Library',exact:true}).click();await page.waitForFunction(id=>document.querySelector('select[aria-label="research conversation"]')?.value===id,sharedConversation);assert.equal(await page.getByLabel('research conversation',{exact:true}).inputValue(),sharedConversation);assert.equal(await page.getByLabel('research message').inputValue(),'Unsent shared research draft');await page.getByLabel('research message').fill('');assert.equal(await page.getByLabel('research task',{exact:true}).count(),0);await page.getByRole('button',{name:'Claim',exact:true}).click();await page.getByLabel('New claim').fill('For every integer n, n + 0 = n.');await page.getByRole('button',{name:'Add claim',exact:true}).click();assert.equal(await page.getByRole('heading',{name:'Notes & relationships'}).count(),0);
 const pdf=Buffer.from('%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 300 300]>>endobj\ntrailer<</Root 1 0 R>>\n%%EOF');await page.locator('input[type=file]').setInputFiles({name:'fixture.pdf',mimeType:'application/pdf',buffer:pdf});await page.getByRole('button',{name:'fixture PDF · Unread',exact:false}).click();await page.getByRole('region',{name:'Read fixture',exact:true}).waitFor();await page.getByRole('button',{name:'Connections',exact:true}).click();await page.getByRole('group',{name:'Source connections graph'}).waitFor();await page.getByLabel('research message').fill('Library follow-up draft');await page.getByRole('button',{name:'Research',exact:true}).click();assert.equal(await page.getByLabel('research message').inputValue(),'Library follow-up draft');await page.getByLabel('research message').fill('');await page.getByRole('button',{name:'Library',exact:true}).click();await page.getByRole('button',{name:'Connections',exact:true}).click();await page.screenshot({path:'.local/qa/library-redesign.png'});
 await page.getByRole('button',{name:'Lean Certificates',exact:true}).click();if(!await page.locator('.projectCertificateChecks').evaluate(el=>el.open))await page.locator('.projectCertificateChecks>summary').click();await page.getByRole('button',{name:'Inspect project'}).click();await page.getByText('Check history (1)',{exact:true}).waitFor();assert.equal(await page.getByRole('heading',{name:'not configured',exact:true}).count(),0);assert.equal(await page.locator('textarea.code').count(),0);assert.ok(await page.locator('.resizablePane > .panel').evaluateAll(els=>els.every(e=>e.getBoundingClientRect().right<=innerWidth)));await page.screenshot({path:'.local/qa/lean-redesign.png'});
 await page.getByRole('button',{name:'Write-up',exact:true}).click();await page.getByLabel('Manuscript source').fill('# Final manuscript fixture\n\nA test of \\(x^2\\) rendering.');await page.locator('.paperPreview .katex').waitFor();await page.getByLabel('Write-up default format', {exact:true}).click();await page.locator('.writeupFormatOptions input[type=file]').setInputFiles({name:'figure.png',mimeType:'image/png',buffer:await fs.readFile('public/workbench-mark.png')});await page.waitForFunction(()=>document.querySelector('.paperPreview img')?.naturalWidth>0);await page.getByLabel('Write-up default format', {exact:true}).click();await page.getByRole('button',{name:'LaTeX',exact:false}).first().click();assert.equal(await page.getByLabel('Manuscript source').inputValue(),'');await page.getByLabel('Manuscript source').fill('\\documentclass{article}\n\\begin{document}\nExplicit test manuscript.\n\\end{document}');await page.getByRole('button',{name:'Render document',exact:true}).waitFor();await page.getByRole('button',{name:'Render document',exact:true}).click();await page.getByRole('region',{name:'Publication PDF',exact:true}).waitFor({timeout:120000});const pdfUrl=await page.getByRole('link',{name:'Open PDF',exact:true}).getAttribute('href');const rendered=await fetch(url+pdfUrl);assert.equal((await rendered.arrayBuffer()).byteLength>1000,true);await page.getByRole('button',{name:'Markdown',exact:false}).first().click();assert.ok((await page.getByLabel('Manuscript source').inputValue()).includes('Final manuscript fixture'));await page.getByRole('button',{name:'Bibliography',exact:true}).click();await page.getByLabel('BibTeX bibliography').fill('@article{fixture2026,title={Fixture only},author={Example, A},year={2026}}');await page.getByRole('button',{name:'Check syntax'}).click();await page.getByText('1 entries parsed.',{exact:false}).waitFor();await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'LaTeX',exact:false}).first().click();await page.waitForFunction(old=>document.querySelector('.pdfToolbar a')?.getAttribute('href')!==old,pdfUrl);assert.equal(await page.getByText('Source or bibliography changed. Render again to update the PDF.').count(),0);await page.getByRole('button',{name:'Markdown',exact:false}).first().click();await page.getByRole('button',{name:'Save source',exact:true}).click();await page.waitForFunction(()=>!localStorage.getItem('axiovela-math-pending-workspace'));await page.screenshot({path:'.local/qa/writeup-redesign.png'});
 await page.getByLabel('Write-up default format', {exact:true}).click();await page.getByRole('button',{name:'Submission checks',exact:true}).click();await page.getByRole('dialog',{name:'Submission checks'}).waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByLabel('Manuscript source').fill('# Recovery fixture');await page.reload();await page.getByRole('heading',{name:'Executive summary'}).waitFor();await page.getByRole('button',{name:'Write-up',exact:true}).click();assert.equal(await page.getByLabel('Manuscript source').inputValue(),'# Recovery fixture');await page.getByRole('button',{name:'New project',exact:true}).click();await page.getByLabel('Project folder',{exact:true}).fill(path.join(data,'chosen-parent/Created project fixture'));await page.getByRole('button',{name:'Open or create',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.ok(await fs.stat(path.join(data,'chosen-parent/Created project fixture/axiovela-math.project.json')));
 // Closing a tab saves its drafts and preserves the project for reopening.
 await page.getByRole('button',{name:'Write-up',exact:true}).click();await page.getByLabel('Manuscript source').fill('# Closed tab draft');
 await page.getByRole('button',{name:'Close Created project fixture',exact:true}).click();
 await page.getByLabel('File menu').click();await page.getByRole('button',{name:'Open project…',exact:true}).click();await page.getByRole('button',{name:'Created project fixture · closed',exact:true}).click();await page.getByRole('dialog',{name:'Project settings',exact:true}).waitFor({state:'hidden'});
 assert.equal(await page.getByLabel('Manuscript source').inputValue(),'# Closed tab draft');
 // The arXiv UI uses the importer, handles both URL forms and IDs, and avoids duplicates.
 const uploaded=await fetch(url+'/api/papers',{method:'POST',body:pdf}).then(r=>r.json());let imports=0;
 await page.route('**/api/papers/arxiv',route=>{imports++;return route.fulfill({json:{paper:{id:uploaded.id,arxivId:'2302.03660v2',title:'ArXiv import fixture',authors:['A. Author'],published:'2023-02-07',sourceUrl:'https://arxiv.org/abs/2302.03660v2',notes:'',citationKey:'arxiv230203660v2',read:false}}});});
 await page.getByRole('button',{name:'Library',exact:true}).click();
 for(const input of ['https://arxiv.org/abs/2302.03660','https://arxiv.org/pdf/2302.03660','2302.03660']){
  await page.getByLabel('Search library').fill(input);await page.getByLabel('Search library').press('Enter');await page.getByRole('button',{name:'ArXiv import fixture PDF · Unread',exact:false}).waitFor();
 }
 assert.equal(imports,1);await page.getByRole('button',{name:'BibTeX',exact:true}).click();assert.match(await page.getByLabel('BibTeX bibliography').inputValue(),/@misc\{arxiv230203660v2/);await page.getByRole('button',{name:'Close dialog'}).click();
 await page.getByLabel('Search library').fill('http://127.0.0.1/private-source');await page.getByLabel('Search library').press('Enter');await page.getByText('Link saved. Preview unavailable:',{exact:false}).waitFor();assert.equal(imports,1);
 assert.equal(await page.locator('.helpMenu').count(),0);assert.equal(await page.locator('.saveState').count(),0);
 const names=await page.locator('.projectTab .tabClose').evaluateAll(els=>els.map(e=>e.getAttribute('aria-label')));for(const name of names)await page.getByRole('button',{name,exact:true}).click();await page.getByRole('heading',{name:'No open project'}).waitFor();await page.reload();await page.getByRole('heading',{name:'No open project'}).waitFor();await page.getByRole('button',{name:'Open a project',exact:true}).click();await page.getByRole('button',{name:'Created project fixture · closed',exact:true}).click();await page.getByRole('dialog',{name:'Project settings',exact:true}).waitFor({state:'hidden'});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/qa/mobile-redesign.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 const result={passed:true,checks:['project save and reload','keyboard panel resizing','persistent layout reset','real Codex fixture chat','platform-specific provider setup','PDF reader','source and claim graph view','Lean checks without source code','independent final manuscript formats','math normalization','bibliography parsing','actual project folder creation','mobile overflow','no runtime errors','shared Research/Library history and drafts','request-directed chat without task selector','actual UI LaTeX render and PDF response','bibliography refreshes PDF automatically','native dialog Escape','unsaved manuscript recovery','close and reopen project tabs with saved drafts','close all tabs and reopen after reload','arXiv URLs and IDs import once with bibliography','non-arXiv links save with an honest preview fallback','updates only in Help'],checkedAt:new Date().toISOString()};await fs.writeFile('docs/ui-validation.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
}catch(e){if(page){await fs.mkdir('.local/qa',{recursive:true});await page.screenshot({path:'.local/qa/failure.png'});console.error(await page.locator('dialog').evaluateAll(ds=>ds.map(d=>({open:d.open,text:d.textContent.slice(0,1400)}))));}console.error(logs);throw e;}finally{await browser?.close();service.kill('SIGTERM');await new Promise(r=>service.once('exit',r));await fs.rm(data,{recursive:true,force:true});}
