import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {chromium} from 'playwright';
const data=await fs.mkdtemp(path.join(os.tmpdir(),'axiovela-math-ui-'));
const port=8792,url=`http://127.0.0.1:${port}`;
const env={...process.env,PORT:String(port),AXIOVELA_MATH_DATA:data,WORKBENCH_PROVIDER_SETTINGS_PATH:path.join(data,'private/providers.json'),WORKBENCH_CODEX_PATH:path.resolve('scripts/fixtures/assistant-rpc.mjs'),AXIOVELA_LAKE_PATH:'/nonexistent/fixture-lake'};
for(const id of ['CLAUDE','GEMINI','OPENCODE','PI'])env[`WORKBENCH_${id}_PATH`]=path.resolve('scripts/fixtures/provider-cli.mjs');
for(const key of ['OPENAI_API_KEY','ANTHROPIC_API_KEY','GEMINI_API_KEY','GOOGLE_API_KEY','WORKBENCH_COMPATIBLE_API_KEY'])delete env[key];
const service=spawn(process.execPath,['server/index.mjs'],{env,stdio:'pipe'});let logs='';service.stderr.on('data',x=>logs+=x);
let browser,page;
try{
 for(let i=0;i<100;i++){try{if((await fetch(url+'/api/state')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 assert.equal((await fetch(url+'/api/state',{headers:{Origin:'https://untrusted.example'}})).status,403);
 browser=await chromium.launch({headless:true});page=await browser.newPage({viewport:{width:1600,height:1040}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.getByRole('heading',{name:'Executive summary'}).waitFor();
 await page.getByRole('button',{name:'Edit',exact:true}).first().click();await page.getByLabel('Question or direction').fill('Fixture: examine a precise mathematical conjecture.');await page.getByLabel('Executive summary',{exact:true}).fill('## Current approach\n\nA fixture for the revised workspace. No research result is asserted.');await page.getByRole('button',{name:'Done',exact:true}).click();
 const splitter=page.getByRole('separator').first();const before=await splitter.getAttribute('aria-valuenow');await splitter.focus();await page.keyboard.press('ArrowRight');assert.notEqual(await splitter.getAttribute('aria-valuenow'),before);await page.getByRole('button',{name:'Save workspace',exact:true}).click();await page.getByText('● Saved locally').waitFor();await page.reload();assert.notEqual(await page.getByRole('separator').first().getAttribute('aria-valuenow'),before);await page.getByRole('button',{name:'Reset layout'}).click();assert.equal(await page.getByRole('separator').first().getAttribute('aria-valuenow'),before);
 await page.getByRole('button',{name:'Choose research model and provider'}).click();await page.getByRole('button',{name:'Use model',exact:true}).waitFor();await page.getByRole('button',{name:'Use model',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 await page.getByLabel('research message').fill('FIXTURE_CODE');await page.getByRole('button',{name:'Send message',exact:true}).click();await page.getByText('Get-Location',{exact:false}).waitFor();
 await page.getByRole('button',{name:'Choose research model and provider'}).click();await page.locator('dialog[open] select').first().selectOption('claude');await page.getByText('Install or connect Claude Code',{exact:true}).waitFor();await page.getByRole('button',{name:'Windows',exact:true}).click();await page.getByText('npm.cmd install -g @anthropic-ai/claude-code',{exact:true}).waitFor();await page.getByRole('button',{name:'Close model picker'}).click();
 await fs.mkdir('.local/qa',{recursive:true});await page.screenshot({path:'.local/qa/research-redesign.png'});
 const sharedConversation=await page.getByLabel('research conversation',{exact:true}).inputValue();await page.getByLabel('research message').fill('Unsent shared research draft');await page.getByRole('button',{name:'Library',exact:true}).click();await page.waitForFunction(id=>document.querySelector('select[aria-label="research conversation"]')?.value===id,sharedConversation);assert.equal(await page.getByLabel('research conversation',{exact:true}).inputValue(),sharedConversation);assert.equal(await page.getByLabel('research message').inputValue(),'Unsent shared research draft');await page.getByLabel('research message').fill('');assert.equal(await page.getByLabel('research task',{exact:true}).count(),0);await page.getByRole('separator',{name:'Resize library-detail panels 1 and 2'}).focus();await page.keyboard.press('ArrowDown');await page.getByRole('button',{name:'Claim',exact:true}).click();await page.getByLabel('New claim').fill('For every integer n, n + 0 = n.');await page.getByRole('button',{name:'Add claim',exact:true}).click();await page.getByLabel('Status C1').selectOption('informal-proof');await page.getByLabel('Statement C1').fill('For every natural number n, n + 0 = n.');assert.equal(await page.getByLabel('Status C1').inputValue(),'conjecture');
 const pdf=Buffer.from('%PDF-1.4\n1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 300 300]>>endobj\ntrailer<</Root 1 0 R>>\n%%EOF');await page.locator('input[type=file]').setInputFiles({name:'fixture.pdf',mimeType:'application/pdf',buffer:pdf});await page.getByRole('button',{name:'fixture Unread',exact:false}).click();await page.locator('iframe').waitFor();await page.getByRole('button',{name:'Relationships',exact:true}).click();await page.getByLabel('This item',{exact:true}).selectOption('supports');await page.getByLabel('Another paper or claim').selectOption('claim:C1');await page.getByRole('button',{name:'Add relationship',exact:true}).click();await page.getByRole('button',{name:'Connections',exact:true}).click();await page.getByRole('img',{name:'Connections between papers and mathematical claims'}).waitFor();await page.getByLabel('research message').fill('Library follow-up draft');await page.getByRole('button',{name:'Research',exact:true}).click();assert.equal(await page.getByLabel('research message').inputValue(),'Library follow-up draft');await page.getByLabel('research message').fill('');await page.getByRole('button',{name:'Library',exact:true}).click();await page.getByRole('button',{name:'Connections',exact:true}).click();await page.screenshot({path:'.local/qa/library-redesign.png'});
 await page.getByRole('button',{name:'Lean Certificates',exact:true}).click();await page.getByRole('button',{name:'Inspect project'}).click();await page.getByRole('heading',{name:'not configured',exact:true}).waitFor();assert.equal(await page.locator('textarea.code').count(),0);assert.ok(await page.locator('.resizablePane > .panel').evaluateAll(els=>els.every(e=>e.getBoundingClientRect().right<=innerWidth)));await page.screenshot({path:'.local/qa/lean-redesign.png'});
 await page.getByRole('button',{name:'Write-up',exact:true}).click();await page.getByLabel('Manuscript source').fill('# Final manuscript fixture\n\nA test of \\(x^2\\) rendering.');await page.locator('.paperPreview .katex').waitFor();await page.getByRole('button',{name:'LaTeX',exact:false}).first().click();assert.ok((await page.getByLabel('Manuscript source').inputValue()).includes('documentclass'));await page.getByRole('button',{name:'Render PDF',exact:true}).waitFor();await page.getByRole('button',{name:'Render PDF',exact:true}).click();await page.getByTitle('Publication PDF').waitFor({timeout:120000});const pdfUrl=await page.getByTitle('Publication PDF').getAttribute('src');const rendered=await fetch(url+pdfUrl);assert.equal((await rendered.arrayBuffer()).byteLength>1000,true);await page.getByRole('button',{name:'Markdown',exact:false}).first().click();assert.ok((await page.getByLabel('Manuscript source').inputValue()).includes('Final manuscript fixture'));await page.getByRole('button',{name:'Bibliography',exact:true}).click();await page.getByLabel('BibTeX bibliography').fill('@article{fixture2026,title={Fixture only},author={Example, A},year={2026}}');await page.getByRole('button',{name:'Check syntax'}).click();await page.getByText('1 entries parsed.',{exact:false}).waitFor();await page.getByRole('button',{name:'Close dialog'}).click();await page.getByRole('button',{name:'LaTeX',exact:false}).first().click();await page.getByText('Source or bibliography changed. Render again to update the PDF.').waitFor();await page.getByRole('button',{name:'Markdown',exact:false}).first().click();await page.getByRole('button',{name:'Save source',exact:true}).click();await page.getByText('● Source saved to project').waitFor();await page.screenshot({path:'.local/qa/writeup-redesign.png'});
 await page.getByRole('button',{name:'Submission checks',exact:true}).click();await page.getByRole('dialog',{name:'Submission checks'}).waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});await page.getByLabel('Manuscript source').fill('# Recovery fixture');await page.reload();await page.getByText('○ Recovered unsaved edits').waitFor();await page.getByRole('button',{name:'Write-up',exact:true}).click();assert.equal(await page.getByLabel('Manuscript source').inputValue(),'# Recovery fixture');await page.getByRole('button',{name:'Project',exact:true}).click();await page.getByLabel('New project name').fill('Created project fixture');await page.getByLabel('Parent folder (optional)').fill(path.join(data,'chosen-parent'));await page.getByRole('button',{name:'Create project folder'}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.ok(await fs.stat(path.join(data,'chosen-parent/Created project fixture/axiovela-math.project.json')));
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.local/qa/mobile-redesign.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 const result={passed:true,checks:['project save and reload','keyboard panel resizing','persistent layout reset','real Codex fixture chat','platform-specific provider setup','claim review invalidation','PDF reader','explicit paper-to-claim graph','Lean checks without source code','independent final manuscript formats','math normalization','bibliography parsing','actual project folder creation','mobile overflow','no runtime errors','shared Research/Library history and drafts','Library vertical resizing','request-directed chat without task selector','actual UI LaTeX render and PDF response','bibliography invalidates PDF','native dialog Escape','unsaved manuscript recovery'],checkedAt:new Date().toISOString()};await fs.writeFile('docs/ui-validation.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
}catch(e){if(page){await fs.mkdir('.local/qa',{recursive:true});await page.screenshot({path:'.local/qa/failure.png'});console.error(await page.locator('dialog').evaluateAll(ds=>ds.map(d=>({open:d.open,text:d.textContent.slice(0,1400)}))));}console.error(logs);throw e;}finally{await browser?.close();service.kill('SIGTERM');await new Promise(r=>service.once('exit',r));await fs.rm(data,{recursive:true,force:true});}
