import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,Check,FlaskConical,FolderOpen,RefreshCw,X} from 'lucide-react';
import {request} from './ui.jsx';
export function MetricTable({values,limit=24}){const rows=[];function visit(v,prefix='',depth=0){if(rows.length>=limit||depth>5)return;if(v&&typeof v==='object'){for(const [key,value] of Object.entries(v))visit(value,prefix?`${prefix} · ${key}`:key,depth+1);}else if(v!==undefined&&v!==null)rows.push([prefix,String(v)]);}visit(values);return rows.length?<div className="evidenceTable"><table><tbody>{rows.map(([key,value])=><tr key={key}><th>{key.replaceAll('_',' ')}</th><td>{value}</td></tr>)}</tbody></table></div>:<p className="hint">No measurements were recorded.</p>;}
export default function ExperimentBridge({project,beforeImport,onImported,onClose,existing=[]}){
 const dialog=useRef(),heading=useRef();const [step,setStep]=useState(0),[sources,setSources]=useState([]),[source,setSource]=useState(null),[runs,setRuns]=useState([]),[warnings,setWarnings]=useState([]),[selected,setSelected]=useState({}),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[folder,setFolder]=useState(''),[claimId,setClaimId]=useState(''),[claim,setClaim]=useState(''),[kind,setKind]=useState('observation'),[note,setNote]=useState('');
 const operation=useRef(crypto.randomUUID());const choices=runs.filter(r=>selected[r.key]);
 async function work(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function refresh(){const r=await request('/api/bridge/sources');setSources(r.sources);}
 useEffect(()=>{dialog.current.showModal();work(refresh);},[]);useEffect(()=>{heading.current?.focus();},[step]);
 async function choose(s){await work(async()=>{const r=await request('/api/bridge/runs?source='+s.id);setSource(r.source);setRuns(r.runs);setWarnings(r.warnings);setSelected({});setStep(1);operation.current=crypto.randomUUID();});}
 async function browse(manual=false){await work(async()=>{let chosen=manual?folder:null;if(!manual&&window.methodflowDesktop?.chooseExperimentProject){chosen=await window.methodflowDesktop.chooseExperimentProject();if(!chosen)return;}const r=await request('/api/bridge/sources',{method:'POST',body:JSON.stringify(chosen?{folder:chosen}:{})});await refresh();if(r.source){const data=await request('/api/bridge/runs?source='+r.source.id);setSource(data.source);setRuns(data.runs);setWarnings(data.warnings);setSelected({});setStep(1);}});}
 async function capture(){await work(async()=>{await beforeImport();const result=await request('/api/bridge/evidence?project='+project.id,{method:'POST',body:JSON.stringify({requestId:operation.current,sourceId:source.id,runs:choices.map(r=>({key:r.key,fingerprint:r.fingerprint,files:selected[r.key]}))})});await onImported(result.items,{claimId,claim,kind,note});onClose();});}
 const titles=['Choose your Axiovela project','Choose experiments','Bring evidence into your research'];
 return <dialog className="modal appDialog bridgeDialog" ref={dialog} aria-labelledby="bridge-title" onCancel={e=>{if(busy)e.preventDefault();else onClose();}}><div className="modalHeader"><div><span className="eyebrow">EXPERIMENTS → MATHEMATICAL IDEAS</span><h2 id="bridge-title" tabIndex={-1} ref={heading}>{titles[step]}</h2></div><button className="icon" aria-label="Close experiment import" disabled={busy} onClick={onClose}><X size={18}/></button></div><ol className="bridgeSteps" aria-label="Import progress">{['Project','Experiments','Review'].map((s,i)=><li key={s} aria-current={i===step?'step':undefined} className={i===step?'current':''}>{i<step?<Check size={13}/>:i+1} {s}</li>)}</ol>
 {error&&<p className="inlineError" role="alert">{error}</p>}
 {step===0&&<><p>Bring saved experiments from Axiovela into this research project. We’ll keep a copy of the results you choose.</p><div className="bridgeProjects">{sources.map(s=><button key={s.id} disabled={busy||!s.available} onClick={()=>choose(s)}><FlaskConical size={22}/><span><strong>{s.name}</strong><small>{s.available?s.question||'Axiovela project':'Not available on this computer right now'}</small></span></button>)}</div>{!sources.length&&!busy&&<p className="empty">No recent Axiovela project was found. Choose it once, and we’ll remember it here.</p>}<div className="row"><button onClick={()=>browse()} disabled={busy}><FolderOpen size={15}/>Choose another project…</button><button disabled={busy} onClick={()=>work(refresh)}><RefreshCw size={13}/>Refresh</button></div><details><summary>More options</summary><label>Project location<input value={folder} onChange={e=>setFolder(e.target.value)} placeholder="Optional: paste a project location"/></label><button disabled={busy||!folder.trim()} onClick={()=>browse(true)}>Find project</button></details></>}
 {step===1&&<><p>From <strong>{source.name}</strong>. Choose up to 20 finished experiments. Failed experiments are available too.</p><input aria-label="Find experiments" placeholder="Find an experiment by name…" value={search} onChange={e=>setSearch(e.target.value)}/>{warnings.map((w,i)=><p className="hint" key={i}>{w}</p>)}<div className="experimentChoices">{runs.filter(r=>(r.name+' '+r.experiment).toLowerCase().includes(search.toLowerCase())).map(r=><article key={r.key} className={selected[r.key]?'selected':''}><label className="experimentChoice"><input type="checkbox" aria-label={`Include ${r.name}`} checked={!!selected[r.key]} disabled={busy||['running','queued'].includes(r.status)||(!selected[r.key]&&choices.length>=20)} onChange={e=>setSelected(s=>{const next={...s};if(e.target.checked)next[r.key]=r.attachments.map(a=>a.key);else delete next[r.key];return next;})}/><span><strong>{r.name}</strong><small>{r.experiment} · {r.status==='complete'?'Completed':r.status} {r.completedAt?'· '+new Date(r.completedAt).toLocaleDateString():''}</small></span></label>{existing.some(e=>!e.removed&&e.sourceId===source.id&&e.runKey===r.key)&&<p className="hint">{existing.some(e=>!e.removed&&e.sourceId===source.id&&e.fingerprint===r.fingerprint)?'A copy of these results is already in Library.':'A previous version is in Library. This will add a separate copy.'}</p>}{r.summary&&<p>{r.summary}</p>}{['running','queued'].includes(r.status)&&<p className="hint">This experiment is still active. Refresh after it finishes.</p>}<details><summary>Measurements and included figures</summary><MetricTable values={r.metrics} limit={8}/>{r.attachments.map(a=><label className="bridgeFile" key={a.key}><input type="checkbox" checked={!!selected[r.key]?.includes(a.key)} disabled={busy||!selected[r.key]} onChange={e=>setSelected(s=>({...s,[r.key]:e.target.checked?[...s[r.key],a.key]:s[r.key].filter(k=>k!==a.key)}))}/>{a.name} <small>{(a.bytes/1024).toFixed(0)} KB</small></label>)}{r.omissions.map((m,i)=><p className="hint" key={i}>{m}</p>)}<p className="hint">Measurements, parameters and the recorded method are included. Source code, datasets and chat histories stay in Axiovela.</p></details></article>)}</div>{!runs.length&&<p className="empty">No saved experiments yet. Complete an experiment in Axiovela, then refresh this list.</p>}<button disabled={busy} onClick={()=>choose(source)}><RefreshCw size={13}/>Refresh experiments</button></>}
 {step===2&&<><p><strong>{choices.length} experiment{choices.length===1?'':'s'}</strong> will be added to Library in <strong>{project.name}</strong>.</p><ul className="bridgeReview">{choices.map(r=><li key={r.key}><strong>{r.name}</strong><span>{selected[r.key].length} saved figure{selected[r.key].length===1?'':'s'} · measurements and method</span></li>)}</ul><label>What would you like to explore?<select value={kind} onChange={e=>setKind(e.target.value)}><option value="observation">An observation or pattern</option><option value="counterexample">A possible counterexample</option><option value="witness">A candidate exact witness</option></select></label><label>Connect to a mathematical claim (optional)<select value={claimId} onChange={e=>setClaimId(e.target.value)}><option value="">Keep in Library for now</option>{project.claims.map(c=><option key={c.id} value={c.id}>{c.id}: {c.statement.slice(0,100)}</option>)}<option value="new">Create a new conjecture…</option></select></label>{claimId==='new'&&<label>New conjecture<textarea value={claim} onChange={e=>setClaim(e.target.value)} placeholder="State the mathematical idea you want to investigate."/></label>}<label>Your interpretation (optional)<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="What do these experiments suggest? What still needs checking?"/></label><p className="notice">These results will be saved as experimental evidence. Linking them to a claim does not mark it as proved.</p></>}
 <div className="bridgeFooter"><button disabled={busy||step===0} onClick={()=>setStep(s=>s-1)}><ArrowLeft size={14}/>Back</button><span role="status">{busy?(step===2?'Saving your evidence…':'Reading saved experiments…'):step===1?`${choices.length} selected`:''}</span>{step===1&&<button className="primary" disabled={busy||!choices.length} onClick={()=>{operation.current=crypto.randomUUID();setStep(2);}}>Review selection</button>}{step===2&&<button className="primary" disabled={busy||(claimId==='new'&&!claim.trim())} onClick={capture}>Add to Library</button>}</div></dialog>;
}
